### ISSUE TITLE
Error When Exporting mp4

### ISSUE THREAD

**Issue by linklight2** [Djdefrag/QualityScaler#101]
![Screenshot 2024-09-06 174742](https://github.com/user-attachments/assets/318d52be-3081-4547-9388-752eb00297c7)

Shows up when exporting with the settings below, tried x264 and x265

![Screenshot 2024-09-06 175328](https://github.com/user-attachments/assets/f6270a9e-be23-416e-8216-fd655f25adf8)

**Comment by linklight2** [comment]
Updated: Happens with all ai models and different video too, reproducible on Fluidframes as well

**Comment by Djdefrag** [comment]
Hi my friend,

You need to download new version of ffmpeg.exe and put it in QualityScaler/Assets folder.

1. Go to this site (https://www.gyan.dev/ffmpeg/builds/)
2. Download one of this zip
![364706459-358e9543-13ff-4a1c-bbbb-134ef05d98a8](https://github.com/user-attachments/assets/6bbc7c1a-92ba-498c-9e02-fd858d2ba32b)

3. Extract ffmpeg.exe from the downloaded .zip
4. Copy ffmpeg.exe to QualityScaler/Assets

unfortunately I can't upload the new version to github because it weighs too much and github won't let me****

**Comment by ItsFrankieD** [comment]
Could you possibly include this step in the "Make it work by yourself" section of the README?
