### ISSUE TITLE
QualityScaler.exe is listed as trojan

### ISSUE THREAD

**Issue by IMPOX** [Djdefrag/QualityScaler#44]
Hi there, after last release of QS 2.6, when I unzip the folder Windows Defender lists the Quality Scaler executable file as a trojan and deletes it instantly, preventing me from using it.
![Screenshot 2023-10-02 120610](https://github.com/Djdefrag/QualityScaler/assets/42870562/e5c3fd71-70bc-4391-a5fa-de3b354645a8)

**Comment by Djdefrag** [comment]
Hi my friend,

yes, this is a known issued caused by the pyinstaller tool used to pack the .exe.

https://stackoverflow.com/questions/69528371/pyinstaller-convert-to-exe-virus-detecting

I'm trying to resolve the issue somehow, to resolve you can try to disable Defender before extracting QualityScaler :)

**Comment by Djdefrag** [comment]
Hi my friend, little update about this problem.

It seems that the newer Pyinstaller 6.0 have this problem, while 5.0 don t. 

So next release i will use 5.0 to build the app.

Using 5.0 to test the issue: https://www.virustotal.com/gui/file/6eb3d5e0a876eb29b09de2643ec4d42e630e450875991fcae50e3550b7bf5cf2?nocache=1
