### ISSUE TITLE
Missing "AI" folder and models?

### ISSUE THREAD

**Issue by Funzoomi** [Djdefrag/QualityScaler#47]
![QualityScalerScreenshot2](https://github.com/Djdefrag/QualityScaler/assets/43100669/170bd685-bf0b-4699-96b8-1f2dc40835a1)

There is no "AI" folder or the pth models? Was that something I should have created and dl'ed myself?

**Comment by Djdefrag** [comment]
Hi my friend,

yes the AI folder is not present because is too heavy for Github, if you contact me on Telegram i will send the AI models. (https://linktr.ee/j3ngystudio)

Or you can download them from the github of any AI research,  

- BSRGAN - https://github.com/cszn/BSRGAN
- Real-ESRGAN - https://github.com/xinntao/Real-ESRGAN
- SAFMN - https://github.com/sunny2109/SAFMN

**Comment by zackees** [comment]
dude put this in the readme

**Comment by Djdefrag** [comment]
Fixed, thanks to @zackees  😊

**Comment by zackees** [comment]
This has been solved with a PR that I submitted. Now after git clone it should just work.

**Comment by FurkanGozukara** [comment]
> Hi my friend,
> 
> yes the AI folder is not present because is too heavy for Github, if you contact me on Telegram i will send the AI models. (https://linktr.ee/j3ngystudio)
> 
> Or you can download them from the github of any AI research,
> 
> * BSRGAN - https://github.com/cszn/BSRGAN
> * Real-ESRGAN - https://github.com/xinntao/Real-ESRGAN
> * SAFMN - https://github.com/sunny2109/SAFMN

you know these are pth but your software  looking onnx

where can we download onnx all models?
