### ISSUE TITLE
QualityScaler.exe is marked as Trojan:Win32/Wacatac.B!ml by Windows Defender

### ISSUE THREAD

**Issue by term-est** [Djdefrag/QualityScaler#5]
I don't know if this is a false positive by Wİndows Defender or not. [VirusTotal](https://www.virustotal.com/gui/file/312379592aeff70993bd2a38f3d0407793fc6abaeba1fad22a3d3dfbd4eca5fb/detection)   also doesn't like the distributed executable in the [releases page](https://github.com/Djdefrag/QualityScaler/releases/tag/2.1.0)

The file hash is
```
CRC32: CF09368D
MD5: 2486FB18B943A60793F704968DD262AE
SHA-1: 3775464FDA4D52AB6DF60C83198EF4B16E470F6C
SHA-256:	312379592aeff70993bd2a38f3d0407793fc6abaeba1fad22a3d3dfbd4eca5fb
```
I tried building it myself (cpython 3.10) but my build failed due to `Could not find a version that satisfies the requirement pytorch-directml`, not really a python guy so I left it there. 

Can you share a reproducible build instructions with us so that we can compare executable hashes?

**Comment by Djdefrag** [comment]
Hi, I don t know how to resolve this issue of Defender...

For the 2 AI models you can find them here, i can t upload on GitHub because they are too heavy: https://drive.google.com/drive/folders/13kfr3qny7S2xwG9h7v95F5mkWs0OmU0D

Ah yes, pytorch-directml now support python 3.6 to python 3.8 so python 3.10 is not compatible

**Comment by Djdefrag** [comment]
Hi, i made some research about this problem. It seems that exe built with PyInstaller (the library used to build my Py code in exe) are affected by this bug. I confirm absolutely that is a false positive. Sorry for the inconvenience :(
