### ISSUE TITLE
Program often freezes during upscaling long video

### ISSUE THREAD

**Issue by linklight2** [Djdefrag/QualityScaler#70]
I have an Nvidia RTX 4070 with 12Gb of Vram, yet the program often crashes when upscaling long forms of video content. I think it's a crash or freeze in relation to running out of Vram oddly enough, as I can consistently get the program to run longer on a lower gb limit (8gb). The program will still crash eventually however. 

The video in question I was looking to upscale was Men in Black 1. As an older movie, it was captured in... Questionable quality, and I wanted to use this program to upscale the movie to watch in a higher resolution. Upscaling to even 1080p takes hours even on my machine - and the random freezes when nearing competion (ex: Upscaling video 88.76%) really suck. Even though the folder the upscaler makes of all the movie frames + the upscales the program has already done is still sitting in the destination folder, restarting the process means that the program will re-upscale everything as well, turning an estimated 4hr process into something that can take days.

**Comment by Djdefrag** [comment]
Hi my friend, 

I don't think the problem is related to VRAM, but I think more that it is a hard disk or SSD space problem. Considering that Men in black lasts 1 1/2 hours, we are talking about more or less 150k frames to upscale; so 150k original + 150k upscaled frames to save to disk: I think they can easily take up 100+ GB.

Actually i am working to speed up the video AI upscaling phase using a multithreading approach when the GPU is capable, going 2 to 3 times faster.

Also, I'm working on stop and resume functionality, so the app will not upscale frames already made and saved to disk (given the same option)

**Comment by linklight2** [comment]
I have 1TB available (from a 2tb drive), so I'm not sure it's a space issue. The folder it creates is around 20-60Gb scaled to 1080p when it crashes (doesnt always crash).

**Comment by Djdefrag** [comment]
Hi my friend,

maibe i found the problem, thank you! 

I hope it will fix the issue :)

**Comment by linklight2** [comment]
Ok hopefully, good luck!
