### ISSUE TITLE
how about to implement swinir models?

### ISSUE THREAD

**Issue by zelenooki87** [Djdefrag/QualityScaler#8]
Thank you for this great app. Could you please implement Swinir large and medium models?
Thank you very much in advance!

**Comment by Djdefrag** [comment]
Hi, thank you! 

In reality i'm already working to implement SwinIR models. They seems superior in terms of image quality but they are slower (like 2 or 3 times slower).

I would like to make another product dedicated only to SwinIR models because otherwise if I integrate them into QualityScaler then the app would start to be very heavy. Stay tuned ;)

**Comment by zelenooki87** [comment]
also,if you could implement https://github.com/chaofengc/FeMaSR/ models program would be awesome!

**Comment by Djdefrag** [comment]
Wow thanks. I will gave a look :D

**Comment by zelenooki87** [comment]
hi, @Djdefrag  
any news about new version?

**Comment by Djdefrag** [comment]
Hi @zelenooki87 actually working on it, but I recently changed jobs and can't devote much time to these side projects, sorry
