### ISSUE TITLE
error when processing video on all formats

### ISSUE THREAD

**Issue by pheasantus** [Djdefrag/QualityScaler#95]
preset:
 resolution 848x480 95m:28s 143195 frames
AI input 100% 848x480
AI output x2 1696x960
error:
> 1. Upscaling video 93.78% (01s)
> 1. Upscaling video 93.79% (01s)
> 1. Processing upscaled video
> Error [Errno 22] Invalid argument
> 
> MoviePy error: FFMPEG encountered the following error while writing file F:/\U Pana Boga za piecem 1998.mp4_BSRGANx2_Resize-100_Interpolation-Medium.mp4:
> 
>  b'[mp4 @ 0000026abb4fde80] Could not find tag for codec pcm_s16le in stream #1, codec not currently supported in container\r\nCould not write header for output file #0 (incorrect codec parameters ?): Invalid argument\r\nError initializing output stream 0:0 -- \r\n'
> 
> The video export failed, possibly because the codec specified for the video (libx264) is not compatible with the given extension (mp4). Please specify a valid 'codec' argument in write_videofile. This would be 'libx264' or 'mpeg4' for mp4, 'libtheora' for ogv, 'libvpx for webm. Another possible reason is that the audio codec was not compatible with the video codec. For instance the video extensions 'ogv' and 'webm' only allow 'libvorbis' (default) as avideo codec.
>

**Comment by Djdefrag** [comment]
Hi my friend,

Probably you need to download new version of ffmpeg.exe and put it in QualityScaler/Assets folder.

1. Go to this site (https://www.gyan.dev/ffmpeg/builds/)
2. Download one of this zip

![359510912-465cb92a-8850-4445-8025-02db15b25789](https://github.com/user-attachments/assets/d7b46e79-d3da-48a4-b08a-d2481f73fed2)

3. Extract ffmpeg.exe from the downloaded .zip
4. Copy ffmpeg.exe to QualityScaler/Assets

unfortunately I can't upload the new version to github because it weighs too much and github won't let me

**Comment by pheasantus** [comment]
it worked, thx
