### ISSUE TITLE
MoviePy export error

### ISSUE THREAD

**Issue by Corentin-METROUN** [Djdefrag/QualityScaler#98]
MoviePy error: FFMPEG encountered the following error while writing file C:/Users/name/Documents/Dig Deeper_RealSRx4_Anime_Resize-70_Interpolation-Low.mp4:

 b'[mp4 @ 000001b5fb9ddd00] Could not find tag for codec pcm_s16le in stream #1, codec not currently supported in container
Could not write header for output file #0 (incorrect codec parameters ?): Invalid argument
Error initializing output stream 0:0 --'

The video export failed, possibly because the codec specified for the video (libx264) is not compatible with the given extension (mp4). Please specify a valid 'codec' argument in write_videofile. This would be 'libx264' or 'mpeg4' for mp4, 'libtheora' for ogv, 'libvpx for webm. Another possible reason is that the audio codec was not compatible with the video codec. For instance the video extensions 'ogv' and 'webm' only allow 'libvorbis' (default) as avideo codec.

**Comment by Djdefrag** [comment]
Hi my friend,

Probably you need to download new version of ffmpeg.exe and put it in QualityScaler/Assets folder.

1. Go to this site (https://www.gyan.dev/ffmpeg/builds/)
2. Download one of this zip
![359510912-465cb92a-8850-4445-8025-02db15b25789](https://github.com/user-attachments/assets/83734114-3873-412a-82ae-be78ed244f43)


3.Extract ffmpeg.exe from the downloaded .zip
4. Copy ffmpeg.exe to QualityScaler/Assets

unfortunately I can't upload the new version to github because it weighs too much and github won't let me

**Comment by Corentin-METROUN** [comment]
Hi, just seen it on a previous issue. Thanks !

**Comment by Djdefrag** [comment]
Thanks to you my friend :)
